version: '3.8'
services:
  rabbitmq:
    image: bitnami/rabbitmq:4.0
    environment:
      RABBITMQ_USERNAME: 'admin'
      RABBITMQ_PASSWORD: 'admin'
    ports:
      - 15672:15672
      - 5672:5672
