server:
  port:
    8081

spring:
  rabbitmq:
    host: localhost
    port: 5672

camunda:
  bpm:
    client:
      base-url: http://localhost:8080/engine-rest

app:
  rabbitmq:
    queue-name: registration.requests